import './globals.css'
import { Roboto } from 'next/font/google'
import Header from '@/components/Header'
import AuthProvider from '@/context/auth'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '500']
})

export const metadata = {
  title: 'Short Url ',
  description: 'Make url shorter, generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <AuthProvider>
        <body className={`flex flex-col min-h-screen ${roboto.className}`}>
          <Header />
          <main className='grow bg-fondo text-white flex '>
            <section className='max-w-4xl mx-auto flex w-full'>
              {children}
            </section>
          </main>
        </body>
      </AuthProvider>
    </html>
  )
}
